In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# data preprocessing

In [4]:
df_ecom=pd.read_csv(r'C:\Users\elhad\Videos\Alaa_Essam_Ai_Discovery_Camp\FinalProject\dataset\E-Commerce_data.csv')
df_saas=pd.read_csv(r'C:\Users\elhad\Videos\Alaa_Essam_Ai_Discovery_Camp\FinalProject\dataset\SaaS_Tech_data.csv')

In [5]:
df_ecom.head()

,ticket_id,industry,category,priority,sentiment,title,description,created_date,channel,resolution_time_hours
0,TKT-000002,E-Commerce / Retail,account,high,negative,Account suspended without notification,"Hi,\n\nI logged in to find my account suspende...",2025-05-08,web,8
1,TKT-000004,E-Commerce / Retail,technical,medium,neutral,Website logs me out every few minutes,"Hey,\n\nThe site logs me out every 5 minutes e...",2025-05-22,mobile,48
2,TKT-000008,E-Commerce / Retail,technical,medium,neutral,Website logs me out every few minutes,The site logs me out every 4 minutes even when...,2025-10-04,mobile,96
3,TKT-000011,E-Commerce / Retail,billing,medium,negative,Refund for order ORD-8311097 not received afte...,"Hi,\n\nI cancelled order ORD-8311097 on 2026-0...",2025-08-12,web,96
4,TKT-000013,E-Commerce / Retail,billing,low,positive,Partial refund for order ORD-8529542 is short,"Good afternoon,\n\nI returned 3 items from ord...",2025-05-11,web,24

In [6]:
df_saas.head()

,ticket_id,industry,category,priority,sentiment,title,description,created_date,channel,resolution_time_hours
0,TKT-000001,SaaS / Tech,billing,high,negative,Charged $217 for feature never activated,"Hello,\n\nInvoice includes $217 for Enterprise...",2025-12-06,chat,1
1,TKT-000003,SaaS / Tech,technical,high,negative,SAML SSO broken after v4.1 update,"Good afternoon,\n\nSSO with Azure AD broken si...",2025-05-12,web,8
2,TKT-000009,SaaS / Tech,billing,medium,positive,Annual plan invoiced monthly,"Good afternoon,\n\nSwitched to annual plan on ...",2025-03-09,web,48
3,TKT-000010,SaaS / Tech,billing,low,negative,Mobile app data sync delay 2–6 hours,"Dear support team,\n\nThis is unacceptable — w...",2025-09-08,mobile,72
4,TKT-000012,SaaS / Tech,technical,high,negative,OAuth token refresh returning 401,"Good afternoon,\n\nRefresh requests return 401...",2025-12-21,email,8

In [7]:
df_ecom.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ticket_id              10000 non-null  object
 1   industry               10000 non-null  object
 2   category               10000 non-null  object
 3   priority               10000 non-null  object
 4   sentiment              10000 non-null  object
 5   title                  10000 non-null  object
 6   description            10000 non-null  object
 7   created_date           10000 non-null  object
 8   channel                10000 non-null  object
 9   resolution_time_hours  10000 non-null  int64
dtypes: int64(1), object(9)
memory usage: 781.4+ KB

In [8]:
df_saas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ticket_id              9999 non-null   object
 1   industry               9999 non-null   object
 2   category               9999 non-null   object
 3   priority               9999 non-null   object
 4   sentiment              9999 non-null   object
 5   title                  9999 non-null   object
 6   description            9999 non-null   object
 7   created_date           9999 non-null   object
 8   channel                9999 non-null   object
 9   resolution_time_hours  9999 non-null   int64
dtypes: int64(1), object(9)
memory usage: 781.3+ KB

In [9]:
df_saas.columns

Index(['ticket_id', 'industry', 'category', 'priority', 'sentiment', 'title',
       'description', 'created_date', 'channel', 'resolution_time_hours'],
      dtype='object')

In [10]:
df_ecom.columns

Index(['ticket_id', 'industry', 'category', 'priority', 'sentiment', 'title',
       'description', 'created_date', 'channel', 'resolution_time_hours'],
      dtype='object')

In [11]:
df_saas.duplicated().sum()

0

In [12]:
df_ecom.duplicated().sum()

0

In [13]:
# merge two columns title and description in one column named text
df_ecom['text'] = df_ecom['title'] + ' ' + df_ecom['description']
df_saas['text'] = df_saas['title'] + ' ' + df_saas['description']
# drop the title and description columns
df_ecom.drop(['title', 'description'], axis=1, inplace=True)
df_saas.drop(['title', 'description'], axis=1, inplace=True)

In [14]:
# drop not nedded columns
df_saas.drop(['ticket_id', 'priority', 'industry','sentiment','created_date','channel','resolution_time_hours'], axis=1, inplace=True)
df_ecom.drop(['ticket_id', 'priority', 'industry','sentiment','created_date','channel','resolution_time_hours'], axis=1, inplace=True)

In [15]:
df_saas

       category                                               text
0       billing  Charged $217 for feature never activated Hello...
1     technical  SAML SSO broken after v4.1 update Good afterno...
2       billing  Annual plan invoiced monthly Good afternoon,\n...
3       billing  Mobile app data sync delay 2–6 hours Dear supp...
4     technical  OAuth token refresh returning 401 Good afterno...
...         ...                                                ...
9994    account  Admin cannot assign custom roles Dear support ...
9995    account  Invited user gets Access Denied after acceptin...
9996    account  Custom domain stuck Unverified after 72 hours ...
9997    billing  Still billed for 87 seats after downgrading to...
9998    account  Audit logs missing critical actions Hello,\n\n...

[9999 rows x 2 columns]

In [16]:
df_ecom

       category                                               text
0       account  Account suspended without notification Hi,\n\n...
1     technical  Website logs me out every few minutes Hey,\n\n...
2     technical  Website logs me out every few minutes The site...
3       billing  Refund for order ORD-8311097 not received afte...
4       billing  Partial refund for order ORD-8529542 is short ...
...         ...                                                ...
9995  technical  App crashes at payment on Windows 11 The app c...
9996    account  Cannot see invoices or download receipts To wh...
9997   delivery  Paid for express shipping on ORD-8501404 but s...
9998    account  Account suspended without notification Good mo...
9999   delivery  Damaged item in order ORD-6151431 Good afterno...

[10000 rows x 2 columns]

In [17]:
import string
import re
import nltk
from nltk.corpus import stopwords

# download stopwords
nltk.download('stopwords')

def clean_text(text):
    # remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))
    
    # remove numbers
    text = re.sub(r'\d+', '', text)
    
    # convert to lowercase
    text = text.lower()
    
    # remove stop words
    stop_words = set(stopwords.words('english'))
    text = ' '.join([word for word in text.split() if word not in stop_words])
    
    # remove non-alphabetic characters
    text = re.sub(r'[^a-z\s]', '', text)
    
    # remove extra spaces
    text = ' '.join(text.split())
    
    return text

df_saas['text'] = df_saas['text'].apply(clean_text)
df_ecom['text'] = df_ecom['text'].apply(clean_text)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\elhad/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [18]:
df_ecom

       category                                               text
0       account  account suspended without notification hi logg...
1     technical  website logs every minutes hey site logs every...
2     technical  website logs every minutes site logs every min...
3       billing  refund order ord received days hi cancelled or...
4       billing  partial refund order ord short good afternoon ...
...         ...                                                ...
9995  technical  app crashes payment windows app crashes every ...
9996    account  cannot see invoices download receipts may conc...
9997   delivery  paid express shipping ord standard used hey im...
9998    account  account suspended without notification good mo...
9999   delivery  damaged item order ord good afternoon im serio...

[10000 rows x 2 columns]

In [19]:
df_saas

       category                                               text
0       billing  charged feature never activated hello invoice ...
1     technical  saml sso broken v update good afternoon sso az...
2       billing  annual plan invoiced monthly good afternoon sw...
3       billing  mobile app data sync delay hours dear support ...
4     technical  oauth token refresh returning good afternoon r...
...         ...                                                ...
9994    account  admin cannot assign custom roles dear support ...
9995    account  invited user gets access denied accepting good...
9996    account  custom domain stuck unverified hours dear supp...
9997    billing  still billed seats downgrading hi acme corp do...
9998    account  audit logs missing critical actions hello comp...

[9999 rows x 2 columns]

In [20]:
df_ecom['category'].value_counts()

category
account      2526
technical    2502
delivery     2490
billing      2482
Name: count, dtype: int64

In [21]:
df_saas['category'].value_counts()

category
technical    3306
billing      3296
account      3291
delivery      106
Name: count, dtype: int64

In [22]:
# map the category column to numerical values
category_mapping = {'account':0,'technical':1,'billing':2,'delivery':3}
df_ecom['category'] = df_ecom['category'].map(category_mapping)
df_saas['category'] = df_saas['category'].map(category_mapping)

In [23]:
df_saas

      category                                               text
0            2  charged feature never activated hello invoice ...
1            1  saml sso broken v update good afternoon sso az...
2            2  annual plan invoiced monthly good afternoon sw...
3            2  mobile app data sync delay hours dear support ...
4            1  oauth token refresh returning good afternoon r...
...        ...                                                ...
9994         0  admin cannot assign custom roles dear support ...
9995         0  invited user gets access denied accepting good...
9996         0  custom domain stuck unverified hours dear supp...
9997         2  still billed seats downgrading hi acme corp do...
9998         0  audit logs missing critical actions hello comp...

[9999 rows x 2 columns]

In [24]:
df_ecom

      category                                               text
0            0  account suspended without notification hi logg...
1            1  website logs every minutes hey site logs every...
2            1  website logs every minutes site logs every min...
3            2  refund order ord received days hi cancelled or...
4            2  partial refund order ord short good afternoon ...
...        ...                                                ...
9995         1  app crashes payment windows app crashes every ...
9996         0  cannot see invoices download receipts may conc...
9997         3  paid express shipping ord standard used hey im...
9998         0  account suspended without notification good mo...
9999         3  damaged item order ord good afternoon im serio...

[10000 rows x 2 columns]

In [25]:
# merge two dataframes
df = pd.concat([df_ecom, df_saas], axis=0, ignore_index=True)

In [26]:
df

       category                                               text
0             0  account suspended without notification hi logg...
1             1  website logs every minutes hey site logs every...
2             1  website logs every minutes site logs every min...
3             2  refund order ord received days hi cancelled or...
4             2  partial refund order ord short good afternoon ...
...         ...                                                ...
19994         0  admin cannot assign custom roles dear support ...
19995         0  invited user gets access denied accepting good...
19996         0  custom domain stuck unverified hours dear supp...
19997         2  still billed seats downgrading hi acme corp do...
19998         0  audit logs missing critical actions hello comp...

[19999 rows x 2 columns]

In [28]:
from sklearn.model_selection import train_test_split
X = df['text']
y = df['category']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y, shuffle=True)
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=5000)
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train_tfidf, y_train)
y_pred_rf = rf.predict(X_test_tfidf)
print("Random Forest Classifier:")
print(classification_report(y_test, y_pred_rf))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_rf))
print("Accuracy:", accuracy_score(y_test, y_pred_rf))

Random Forest Classifier:
              precision    recall  f1-score   support

           0       0.97      0.97      0.97      1163
           1       0.97      0.97      0.97      1162
           2       0.98      0.97      0.97      1156
           3       0.96      0.95      0.96       519

    accuracy                           0.97      4000
   macro avg       0.97      0.97      0.97      4000
weighted avg       0.97      0.97      0.97      4000

Confusion Matrix:
[[1133   10   12    8]
 [  17 1129    9    7]
 [  16   17 1116    7]
 [   7   10    7  495]]
Accuracy: 0.96825

In [31]:
lr = LogisticRegression(random_state=42)
lr.fit(X_train_tfidf, y_train)
y_pred_lr = lr.predict(X_test_tfidf)
print("Logistic Regression:")
print(classification_report(y_test, y_pred_lr))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_lr))
print("Accuracy:", accuracy_score(y_test, y_pred_lr))

Logistic Regression:
              precision    recall  f1-score   support

           0       0.97      0.98      0.97      1163
           1       0.97      0.98      0.98      1162
           2       0.98      0.97      0.97      1156
           3       0.97      0.96      0.97       519

    accuracy                           0.97      4000
   macro avg       0.97      0.97      0.97      4000
weighted avg       0.97      0.97      0.97      4000

Confusion Matrix:
[[1136    9   12    6]
 [  15 1136    7    4]
 [  15   15 1120    6]
 [   7    8    5  499]]
Accuracy: 0.97275

In [32]:
import joblib
# Save the model to a file
joblib.dump(lr, 'logistic_regression_model.pkl')
joblib.dump(rf, 'random_forest_model.pkl')

['random_forest_model.pkl']